/* Auto-generated by genmsg_cpp for file /home/intelligentrobotics/ws/orocos/KUKACommander/srv/cart_lin_motion.srv */
#ifndef KUKACOMMANDER_SERVICE_CART_LIN_MOTION_H
#define KUKACOMMANDER_SERVICE_CART_LIN_MOTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "geometry_msgs/Pose.h"



namespace KUKACommander
{
template <class ContainerAllocator>
struct cart_lin_motionRequest_ {
  typedef cart_lin_motionRequest_<ContainerAllocator> Type;

  cart_lin_motionRequest_()
  : position()
  , speed(0.0)
  {
  }

  cart_lin_motionRequest_(const ContainerAllocator& _alloc)
  : position(_alloc)
  , speed(0.0)
  {
  }

  typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _position_type;
   ::geometry_msgs::Pose_<ContainerAllocator>  position;

  typedef double _speed_type;
  double speed;


  typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct cart_lin_motionRequest
typedef  ::KUKACommander::cart_lin_motionRequest_<std::allocator<void> > cart_lin_motionRequest;

typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionRequest> cart_lin_motionRequestPtr;
typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionRequest const> cart_lin_motionRequestConstPtr;



template <class ContainerAllocator>
struct cart_lin_motionResponse_ {
  typedef cart_lin_motionResponse_<ContainerAllocator> Type;

  cart_lin_motionResponse_()
  : success(false)
  {
  }

  cart_lin_motionResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct cart_lin_motionResponse
typedef  ::KUKACommander::cart_lin_motionResponse_<std::allocator<void> > cart_lin_motionResponse;

typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionResponse> cart_lin_motionResponsePtr;
typedef boost::shared_ptr< ::KUKACommander::cart_lin_motionResponse const> cart_lin_motionResponseConstPtr;


struct cart_lin_motion
{

typedef cart_lin_motionRequest Request;
typedef cart_lin_motionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct cart_lin_motion
} // namespace KUKACommander

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b6b2cb4aa38489b14a5e1d87d2bc0d82";
  }

  static const char* value(const  ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb6b2cb4aa38489b1ULL;
  static const uint64_t static_value2 = 0x4a5e1d87d2bc0d82ULL;
};

template<class ContainerAllocator>
struct DataType< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/cart_lin_motionRequest";
  }

  static const char* value(const  ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Pose position\n\
float64 speed\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/cart_lin_motionResponse";
  }

  static const char* value(const  ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::KUKACommander::cart_lin_motionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct cart_lin_motionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::KUKACommander::cart_lin_motionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct cart_lin_motionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<KUKACommander::cart_lin_motion> {
  static const char* value() 
  {
    return "c166c946cf08d3e3a652b057dce18240";
  }

  static const char* value(const KUKACommander::cart_lin_motion&) { return value(); } 
};

template<>
struct DataType<KUKACommander::cart_lin_motion> {
  static const char* value() 
  {
    return "KUKACommander/cart_lin_motion";
  }

  static const char* value(const KUKACommander::cart_lin_motion&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c166c946cf08d3e3a652b057dce18240";
  }

  static const char* value(const KUKACommander::cart_lin_motionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<KUKACommander::cart_lin_motionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/cart_lin_motion";
  }

  static const char* value(const KUKACommander::cart_lin_motionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c166c946cf08d3e3a652b057dce18240";
  }

  static const char* value(const KUKACommander::cart_lin_motionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<KUKACommander::cart_lin_motionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/cart_lin_motion";
  }

  static const char* value(const KUKACommander::cart_lin_motionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // KUKACOMMANDER_SERVICE_CART_LIN_MOTION_H

