/* Auto-generated by genmsg_cpp for file /home/intelligentrobotics/ws/orocos/KUKACommander/srv/move_to_cart_pos.srv */
#ifndef KUKACOMMANDER_SERVICE_MOVE_TO_CART_POS_H
#define KUKACOMMANDER_SERVICE_MOVE_TO_CART_POS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "geometry_msgs/Pose.h"



namespace KUKACommander
{
template <class ContainerAllocator>
struct move_to_cart_posRequest_ {
  typedef move_to_cart_posRequest_<ContainerAllocator> Type;

  move_to_cart_posRequest_()
  : position()
  , time(0.0)
  {
  }

  move_to_cart_posRequest_(const ContainerAllocator& _alloc)
  : position(_alloc)
  , time(0.0)
  {
  }

  typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _position_type;
   ::geometry_msgs::Pose_<ContainerAllocator>  position;

  typedef double _time_type;
  double time;


  typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct move_to_cart_posRequest
typedef  ::KUKACommander::move_to_cart_posRequest_<std::allocator<void> > move_to_cart_posRequest;

typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posRequest> move_to_cart_posRequestPtr;
typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posRequest const> move_to_cart_posRequestConstPtr;



template <class ContainerAllocator>
struct move_to_cart_posResponse_ {
  typedef move_to_cart_posResponse_<ContainerAllocator> Type;

  move_to_cart_posResponse_()
  : success(false)
  {
  }

  move_to_cart_posResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct move_to_cart_posResponse
typedef  ::KUKACommander::move_to_cart_posResponse_<std::allocator<void> > move_to_cart_posResponse;

typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posResponse> move_to_cart_posResponsePtr;
typedef boost::shared_ptr< ::KUKACommander::move_to_cart_posResponse const> move_to_cart_posResponseConstPtr;


struct move_to_cart_pos
{

typedef move_to_cart_posRequest Request;
typedef move_to_cart_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct move_to_cart_pos
} // namespace KUKACommander

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "53db00d1a5eaaae6f83431dafaa7dbfa";
  }

  static const char* value(const  ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x53db00d1a5eaaae6ULL;
  static const uint64_t static_value2 = 0xf83431dafaa7dbfaULL;
};

template<class ContainerAllocator>
struct DataType< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/move_to_cart_posRequest";
  }

  static const char* value(const  ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Pose position\n\
float64 time\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/move_to_cart_posResponse";
  }

  static const char* value(const  ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::KUKACommander::move_to_cart_posRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct move_to_cart_posRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::KUKACommander::move_to_cart_posResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct move_to_cart_posResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<KUKACommander::move_to_cart_pos> {
  static const char* value() 
  {
    return "a112c6298852ba0c08f7b83729504253";
  }

  static const char* value(const KUKACommander::move_to_cart_pos&) { return value(); } 
};

template<>
struct DataType<KUKACommander::move_to_cart_pos> {
  static const char* value() 
  {
    return "KUKACommander/move_to_cart_pos";
  }

  static const char* value(const KUKACommander::move_to_cart_pos&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a112c6298852ba0c08f7b83729504253";
  }

  static const char* value(const KUKACommander::move_to_cart_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<KUKACommander::move_to_cart_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/move_to_cart_pos";
  }

  static const char* value(const KUKACommander::move_to_cart_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a112c6298852ba0c08f7b83729504253";
  }

  static const char* value(const KUKACommander::move_to_cart_posResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<KUKACommander::move_to_cart_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "KUKACommander/move_to_cart_pos";
  }

  static const char* value(const KUKACommander::move_to_cart_posResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // KUKACOMMANDER_SERVICE_MOVE_TO_CART_POS_H

