/* Auto-generated by genmsg_cpp for file /home/intelligentrobotics/ws/orocos/rokon_commander/srv/move_to_pos.srv */
#ifndef ROKON_COMMANDER_SERVICE_MOVE_TO_POS_H
#define ROKON_COMMANDER_SERVICE_MOVE_TO_POS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace rokon_commander
{
template <class ContainerAllocator>
struct move_to_posRequest_ {
  typedef move_to_posRequest_<ContainerAllocator> Type;

  move_to_posRequest_()
  : position()
  , time(0.0)
  {
    position.assign(0.0);
  }

  move_to_posRequest_(const ContainerAllocator& _alloc)
  : position()
  , time(0.0)
  {
    position.assign(0.0);
  }

  typedef boost::array<double, 7>  _position_type;
  boost::array<double, 7>  position;

  typedef double _time_type;
  double time;


  typedef boost::shared_ptr< ::rokon_commander::move_to_posRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokon_commander::move_to_posRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct move_to_posRequest
typedef  ::rokon_commander::move_to_posRequest_<std::allocator<void> > move_to_posRequest;

typedef boost::shared_ptr< ::rokon_commander::move_to_posRequest> move_to_posRequestPtr;
typedef boost::shared_ptr< ::rokon_commander::move_to_posRequest const> move_to_posRequestConstPtr;



template <class ContainerAllocator>
struct move_to_posResponse_ {
  typedef move_to_posResponse_<ContainerAllocator> Type;

  move_to_posResponse_()
  : success(false)
  {
  }

  move_to_posResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::rokon_commander::move_to_posResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokon_commander::move_to_posResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct move_to_posResponse
typedef  ::rokon_commander::move_to_posResponse_<std::allocator<void> > move_to_posResponse;

typedef boost::shared_ptr< ::rokon_commander::move_to_posResponse> move_to_posResponsePtr;
typedef boost::shared_ptr< ::rokon_commander::move_to_posResponse const> move_to_posResponseConstPtr;


struct move_to_pos
{

typedef move_to_posRequest Request;
typedef move_to_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct move_to_pos
} // namespace rokon_commander

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rokon_commander::move_to_posRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rokon_commander::move_to_posRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rokon_commander::move_to_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "76cf5f582f7bb8272bc0b744b891358a";
  }

  static const char* value(const  ::rokon_commander::move_to_posRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x76cf5f582f7bb827ULL;
  static const uint64_t static_value2 = 0x2bc0b744b891358aULL;
};

template<class ContainerAllocator>
struct DataType< ::rokon_commander::move_to_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rokon_commander/move_to_posRequest";
  }

  static const char* value(const  ::rokon_commander::move_to_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rokon_commander::move_to_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[7] position\n\
float64 time\n\
\n\
";
  }

  static const char* value(const  ::rokon_commander::move_to_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rokon_commander::move_to_posRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rokon_commander::move_to_posResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rokon_commander::move_to_posResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rokon_commander::move_to_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::rokon_commander::move_to_posResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokon_commander::move_to_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rokon_commander/move_to_posResponse";
  }

  static const char* value(const  ::rokon_commander::move_to_posResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rokon_commander::move_to_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::rokon_commander::move_to_posResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rokon_commander::move_to_posResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rokon_commander::move_to_posRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct move_to_posRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rokon_commander::move_to_posResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct move_to_posResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<rokon_commander::move_to_pos> {
  static const char* value() 
  {
    return "fb7d8862779c7c886d42a9e27e522fc7";
  }

  static const char* value(const rokon_commander::move_to_pos&) { return value(); } 
};

template<>
struct DataType<rokon_commander::move_to_pos> {
  static const char* value() 
  {
    return "rokon_commander/move_to_pos";
  }

  static const char* value(const rokon_commander::move_to_pos&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rokon_commander::move_to_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fb7d8862779c7c886d42a9e27e522fc7";
  }

  static const char* value(const rokon_commander::move_to_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rokon_commander::move_to_posRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rokon_commander/move_to_pos";
  }

  static const char* value(const rokon_commander::move_to_posRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rokon_commander::move_to_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fb7d8862779c7c886d42a9e27e522fc7";
  }

  static const char* value(const rokon_commander::move_to_posResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rokon_commander::move_to_posResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rokon_commander/move_to_pos";
  }

  static const char* value(const rokon_commander::move_to_posResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROKON_COMMANDER_SERVICE_MOVE_TO_POS_H

